DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  tipo VARCHAR(250) NOT NULL,
  raza VARCHAR (250) NOT NULL,
  color VARCHAR(250) NOT NULL,
  pelaje VARCHAR(250) DEFAULT NULL,
  fecha_nacimiento VARCHAR (250) NOT NULL,
  vacunas VARCHAR (250) NOT NULL,
  estado VARCHAR (250) NOT NULL,
  adoptivo VARCHAR (250) NOT NULL
);